# vim:fileencoding=utf-8:foldmethod=marker

# font_family      monospace
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

font_size 14.0

disable_ligatures cursor

foreground #abb2bf
background #23272e
selection_foreground #d7dae0
selection_background #2c313a

url_color #61afef

#: black
color0 #3f4451
color8 #4f5666

#: red
color1 #e05561
color9 #ff616e

#: green
color2  #8cc265
color10 #a5e075

#: yellow
color3  #d18f52
color11 #f0a45d

#: blue
color4  #4aa5f0
color12 #4dc4ff

#: magenta
color5  #c162de
color13 #de73ff

#: cyan
color6  #42b3c2
color14 #4cd1e0

#: white
color7  #d7dae0
color15 #e6e6e6

inactive_border_color #3e4452
bell_border_color #e06c75
active_border_color #457dff

active_tab_foreground   #3f4451
active_tab_background   #d7dae0
inactive_tab_foreground #d7dae0
inactive_tab_background #3f4451

# Tab Styling
tab_bar_style powerline
tab_powerline_style angled
tab_activity_symbol ""

notify_on_cmd_finish invisible 20
